### ISSUE TITLE
不能将未备案的api.github.com加到小程序后台，是如何处理的

### ISSUE THREAD

**Issue by MakerGYT** [ZhuPeng/mp-githubtrending#6]

**Comment by ZhuPeng** [comment]
本身就不能加的，应该是国外的域名没有备案。我的 github 的 api 都是先过云函数转发的，可以看看 cloud-functions 里面的


> From WeChat Mini Programe: [GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending)
